### ISSUE TITLE
Cannot run basic examples

### ISSUE THREAD

**Issue by FahadRazaKhan** [vista-simulator/vista#6]
Hi,

I am trying to run basic examples (i.e sim_control.py, sim_lidar.py) after the installation, however, it gives me the following error "~/python3.8/site-packages/vista/core/World.py", line 32, in __init__
    self._traces: List[Trace] = [
TypeError: 'NoneType' object is not iterable"

Any help would be appreciated.

Thanks.

**Comment by MarkCodering** [comment]
@FahadRazaKhan I ran to this issue before. Could you paste your code snippet to help us better understand your script? 
### Potential Solution:
The experimental trace path could be download by following the instruction of [this tutorial](https://github.com/aamini/introtodeeplearning/blob/master/lab3/RL.ipynb).
```python3
trace_path = ["./trace/20210726-154641_lexus_devens_center"]
world = vista.World(trace_path, trace_config={'road_width': 4})
```

**Comment by FahadRazaKhan** [comment]
@MarkCodering thanks for your response. Actually, I have just downloaded the Repo from Github, and after the installation, I tried to run the scripts in the example folder. I did not write anything. Do you still need to see the script?

**Comment by MarkCodering** [comment]
@FahadRazaKhan Good morning from Taiwan. If you want to run an example code like **sim_rgb.py** is not possible since the sample code hasn't loaded any trace dataset. You need to add the trace data like the code snippet I gave you in the comment before.

**Comment by FahadRazaKhan** [comment]
@MarkCodering  thanks for your help and good morning from Singapore. I downloaded the traces as you suggested, but I am still getting some warnings and it seems simulator is not working properly. Here is the screenshot of my code sim_control.py (edited in basic examples).


![Screenshot from 2022-06-28 09-48-25](https://user-images.githubusercontent.com/22746659/176071085-95acbc0f-48c2-40f6-b7a3-874c553f295c.png)

**Comment by MarkCodering** [comment]
Good morning, @FahadRazaKhan. I just looked up your reply. I would suggest doing the following to solve the problem potentially.
1. Install openeb dependency and initialize the module with set_env.sh 
2. Choose one trace path to run instead of multiple traces (It might confuse VISTA to run the computation.)

Here is my code snippet for your reference.
```python3
def main():
    trace_path = ["./trace/20210726-154641_lexus_devens_center"]
    world = vista.World(trace_path, trace_config={'road_width': 4})
    car = world.spawn_agent(
        config={
            'length': 5.,
            'width': 2.,
            'wheel_base': 2.78,
            'steering_ratio': 14.7,
            'lookahead_road': True
        })
    display = vista.Display(world)
    state_space_controller = [
        follow_human_trajectory, pure_pursuit_controller
    ][1]

    world.reset()
    display.reset()

    while not car.done:
        action = state_space_controller(car)
        car.step_dynamics(action)

        vis_img = display.render()
        cv2.imshow('Visualize control', vis_img[:, :, ::-1])
        cv2.waitKey(20)
```

**Comment by osugiw** [comment]
> Good morning, @FahadRazaKhan. I just looked up your reply. I would suggest doing the following to solve the problem potentially.
> 
> 1. Install openeb dependency and initialize the module with set_env.sh
> 2. Choose one trace path to run instead of multiple traces (It might confuse VISTA to run the computation.)
> 
> Here is my code snippet for your reference.
> 
> ```python
> def main():
>     trace_path = ["./trace/20210726-154641_lexus_devens_center"]
>     world = vista.World(trace_path, trace_config={'road_width': 4})
>     car = world.spawn_agent(
>         config={
>             'length': 5.,
>             'width': 2.,
>             'wheel_base': 2.78,
>             'steering_ratio': 14.7,
>             'lookahead_road': True
>         })
>     display = vista.Display(world)
>     state_space_controller = [
>         follow_human_trajectory, pure_pursuit_controller
>     ][1]
> 
>     world.reset()
>     display.reset()
> 
>     while not car.done:
>         action = state_space_controller(car)
>         car.step_dynamics(action)
> 
>         vis_img = display.render()
>         cv2.imshow('Visualize control', vis_img[:, :, ::-1])
>         cv2.waitKey(20)
> ```

Hi, the latest repository doesn't contain **trace/20210726-154641_lexus_devens_center**; how could I obtain the data?
Thanks in advance!

**Comment by MarkCodering** [comment]
Hi, @osugiw you can search for the author’s class, introduction to deep learning with its dataset sample

**Comment by ParvezAlam123** [comment]
Hello MarkCodering,
I am not able to run  basic example code:
import argparse
import numpy as np
import os
import cv2

import vista
from vista.utils import transform
from vista.entities.agents.Dynamics import tireangle2curvature





def main():
    trace_path = ["/home/parvez_alam/Downloads/vista_traces/20210726-131322_lexus_devens_center"]  
    world = vista.World(trace_path, trace_config={'road_width': 4})
    car = world.spawn_agent(
        config={
            'length': 5.,
            'width': 2.,
            'wheel_base': 2.78,
            'steering_ratio': 14.7,
            'lookahead_road': True
        })
    display = vista.Display(world)
    #state_space_controller = [
    #   follow_human_trajectory, pure_pursuit_controller
    #][1]

    world.reset()
    display.reset()
    
    while not car.done:
        #action = state_space_controller(car)
        #car.step_dynamics(action)
        
        vis_img = display.render()
        cv2.imshow('Visualize control', vis_img[:, :, ::-1])
        cv2.waitKey(20) 
       
       
       
main() 

error:
2023-08-01 15:15:54,426::WARNING::[vista.entities.sensors.EventCamera.<module>] Fail to import module for event camera. Remember to do source <some-dir>/openeb/build/utils/scripts/setup_env.shCan ignore this if not using it
2023-08-01 15:15:55,130::WARNING::[vista.core.Trace._divide_to_good_segments] No video_label.csv
Traceback (most recent call last):
  File "vista1.py", line 43, in <module>
    main() 
  File "vista1.py", line 37, in main
    vis_img = display.render()
  File "/home/parvez_alam/.local/lib/python3.8/site-packages/vista/core/Display.py", line 227, in render
    patch = PolygonPatch(patch,
  File "/home/parvez_alam/.local/lib/python3.8/site-packages/descartes/patch.py", line 87, in PolygonPatch
    return PathPatch(PolygonPath(polygon), **kwargs)
  File "/home/parvez_alam/.local/lib/python3.8/site-packages/descartes/patch.py", line 62, in PolygonPath
    vertices = concatenate([
  File "/home/parvez_alam/.local/lib/python3.8/site-packages/descartes/patch.py", line 63, in <listcomp>
    concatenate([asarray(t.exterior)[:, :2]] +
IndexError: too many indices for array: array is 0-dimensional, but 2 were indexed

May you help ?

**Comment by masskro0** [comment]
> Hello MarkCodering, I am not able to run basic example code: import argparse import numpy as np import os import cv2
> 
> import vista from vista.utils import transform from vista.entities.agents.Dynamics import tireangle2curvature
> 
> def main(): trace_path = ["/home/parvez_alam/Downloads/vista_traces/20210726-131322_lexus_devens_center"] world = vista.World(trace_path, trace_config={'road_width': 4}) car = world.spawn_agent( config={ 'length': 5., 'width': 2., 'wheel_base': 2.78, 'steering_ratio': 14.7, 'lookahead_road': True }) display = vista.Display(world) #state_space_controller = [ # follow_human_trajectory, pure_pursuit_controller #][1]
> 
> ```
> world.reset()
> display.reset()
> 
> while not car.done:
>     #action = state_space_controller(car)
>     #car.step_dynamics(action)
>     
>     vis_img = display.render()
>     cv2.imshow('Visualize control', vis_img[:, :, ::-1])
>     cv2.waitKey(20) 
> ```
> 
> main()
> 
> error: 2023-08-01 15:15:54,426::WARNING::[vista.entities.sensors.EventCamera.] Fail to import module for event camera. Remember to do source /openeb/build/utils/scripts/setup_env.shCan ignore this if not using it 2023-08-01 15:15:55,130::WARNING::[vista.core.Trace._divide_to_good_segments] No video_label.csv Traceback (most recent call last): File "vista1.py", line 43, in main() File "vista1.py", line 37, in main vis_img = display.render() File "/home/parvez_alam/.local/lib/python3.8/site-packages/vista/core/Display.py", line 227, in render patch = PolygonPatch(patch, File "/home/parvez_alam/.local/lib/python3.8/site-packages/descartes/patch.py", line 87, in PolygonPatch return PathPatch(PolygonPath(polygon), **kwargs) File "/home/parvez_alam/.local/lib/python3.8/site-packages/descartes/patch.py", line 62, in PolygonPath vertices = concatenate([ File "/home/parvez_alam/.local/lib/python3.8/site-packages/descartes/patch.py", line 63, in concatenate([asarray(t.exterior)[:, :2]] + IndexError: too many indices for array: array is 0-dimensional, but 2 were indexed
> 
> May you help ?

@ParvezAlam123 Had the same issue. This reply helped me:
https://github.com/vista-simulator/vista/issues/20#issuecomment-1623287350
